openapi: 3.0.0
info:
  title: Vee's Auth API
  description: Simple API for user authentication
  version: 1.0.0

servers:
  - url: http://localhost:1200

paths:
  /api/signup:
    post:
      summary: Sign up a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '201':
          description: User registered successfully
        '400':
          description: Bad request

  /api/login:
    post:
      summary: Log in a user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
              required:
                - username
                - password
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized

  /api/logout:
    post:
      summary: Log out the user
      responses:
        '200':
          description: Logout successful
